#!/usr/bin/env python3
"""Plot memory timeline from mem_timeline.json files.

Reads one or more mem_timeline.json files (generated by dap_trunk.py)
and produces step-vs-peak-memory graphs.

Usage:
    python plot_memory.py <output_dir1> [output_dir2] ...
    python plot_memory.py /path/to/output --overlay  # overlay multiple runs
"""

import json
import sys
import os
import argparse


def load_timeline(path):
    """Load a mem_timeline.json file."""
    with open(path) as f:
        return json.load(f)


def plot_single(records, title, out_path):
    """Plot a single memory timeline."""
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    steps = [r["step"] for r in records]
    alloc = [r["alloc_mb"] for r in records]
    peak = [r["peak_mb"] for r in records]
    elapsed = [r["elapsed_s"] for r in records]

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(20, 12), sharex=False)

    # Plot 1: Step index vs memory
    x = range(len(steps))
    ax1.fill_between(x, peak, alpha=0.3, color='red', label='Peak')
    ax1.plot(x, alloc, 'b-', linewidth=1.5, label='Allocated')
    ax1.plot(x, peak, 'r--', linewidth=1, label='Peak')
    ax1.set_ylabel('Memory (MB)')
    ax1.set_title(f'{title} — Step vs Memory')
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    # Add step labels on x-axis (rotated)
    # Show every Nth label to avoid overcrowding
    n_labels = min(40, len(steps))
    step_indices = [int(i * len(steps) / n_labels) for i in range(n_labels)]
    ax1.set_xticks(step_indices)
    ax1.set_xticklabels([steps[i][:30] for i in step_indices], rotation=45, ha='right', fontsize=7)

    # Annotate peak changes
    prev_peak = 0
    for i, r in enumerate(records):
        if r["peak_mb"] > prev_peak:
            ax1.annotate(f'+{r["peak_mb"] - prev_peak}MB',
                        xy=(i, r["peak_mb"]),
                        fontsize=6, color='red',
                        xytext=(0, 5), textcoords='offset points')
            prev_peak = r["peak_mb"]

    # Plot 2: Elapsed time vs memory
    ax2.fill_between(elapsed, peak, alpha=0.3, color='red')
    ax2.plot(elapsed, alloc, 'b-', linewidth=1.5, label='Allocated')
    ax2.plot(elapsed, peak, 'r--', linewidth=1, label='Peak')
    ax2.set_xlabel('Elapsed Time (s)')
    ax2.set_ylabel('Memory (MB)')
    ax2.set_title(f'{title} — Time vs Memory')
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Saved: {out_path}")


def plot_overlay(timelines, labels, out_path):
    """Overlay multiple timelines on one plot."""
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(1, 1, figsize=(20, 8))
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']

    for idx, (records, label) in enumerate(zip(timelines, labels)):
        color = colors[idx % len(colors)]
        peak = [r["peak_mb"] for r in records]
        alloc = [r["alloc_mb"] for r in records]
        x = range(len(records))
        ax.plot(x, peak, '--', color=color, linewidth=1, alpha=0.5)
        ax.plot(x, alloc, '-', color=color, linewidth=1.5, label=f'{label} (peak={max(peak)}MB)')

    ax.set_xlabel('Step Index')
    ax.set_ylabel('Memory (MB)')
    ax.set_title('Memory Timeline Comparison')
    ax.legend()
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Saved: {out_path}")


def main():
    parser = argparse.ArgumentParser(description='Plot memory timelines')
    parser.add_argument('dirs', nargs='+', help='Output directories containing mem_timeline.json')
    parser.add_argument('--overlay', action='store_true', help='Overlay all timelines on one plot')
    parser.add_argument('--out', default=None, help='Output image path (default: mem_timeline.png in first dir)')
    args = parser.parse_args()

    timelines = []
    labels = []
    for d in args.dirs:
        path = os.path.join(d, 'mem_timeline.json')
        if not os.path.exists(path):
            print(f"Warning: {path} not found, skipping")
            continue
        timelines.append(load_timeline(path))
        labels.append(os.path.basename(d))

    if not timelines:
        print("No mem_timeline.json files found!")
        sys.exit(1)

    if args.overlay and len(timelines) > 1:
        out_path = args.out or os.path.join(args.dirs[0], 'mem_overlay.png')
        plot_overlay(timelines, labels, out_path)
    else:
        for records, label, d in zip(timelines, labels, args.dirs):
            out_path = args.out or os.path.join(d, 'mem_timeline.png')
            plot_single(records, label, out_path)


if __name__ == '__main__':
    main()
